version: '3.9'

services:
  db:
    container_name: denuncia-backend
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=denuncia-db
    volumes:
      - ./data:/var/lib/postgresql/data
